### ISSUE TITLE
calling `buffer.par_sort_unstable_by_key` from a task calls the task itself

### ISSUE THREAD

**Issue by progval** [rayon-rs/rayon#1083]
Hi,

I have some code that essentially does the following:

1. uses [thread_local](https://docs.rs/thread_local/latest/thread_local/) to have a buffer for each thread
2. calls `my_iterator.into_par_iter().for_each(f)` where
3. `f` is a function that accesses the above thread-local buffer (by holding a mutex), and calls `buffer.par_sort_unstable_by_key(|(src, dst, _)| (*src, *dst));` from time to time then drops the buffer (in the real code, it's flushed to disk). While calling `buffer.par_sort_unstable_by_key`, `f` still holds a mutex to its buffer.

However, from time to time, `f` gets called while `buffer.par_sort_unstable_by_key` is running within the same thread, causing a deadlock.

Here is some code to reproduce the issue:

```rust
use rayon::prelude::*;

use std::sync::Mutex;

struct VerboseMutex<T> {
    creator: std::thread::ThreadId,
    current_owner: Mutex<Option<std::thread::ThreadId>>,
    last_owner: Mutex<Option<std::thread::ThreadId>>,
    inner: Mutex<T>
}

impl<T> VerboseMutex<T> {
    pub fn new(t: T) -> VerboseMutex<T> {
        VerboseMutex {
            creator: std::thread::current().id(),
            current_owner: Mutex::new(None),
            last_owner: Mutex::new(None),
            inner: Mutex::new(t),
        }
    }

    pub fn lock(&self) -> std::sync::LockResult<VerboseGuard<'_, T>> {
        println!("acquiring {:?}", std::thread::current().id());
        let guard = self.inner.lock();
        *self.current_owner.try_lock().unwrap() = Some(std::thread::current().id());
        *self.last_owner.try_lock().unwrap() = Some(std::thread::current().id());
        println!("acquired {:?}", std::thread::current().id());
        Ok(VerboseGuard(&self, guard.unwrap()))
    }

    pub fn try_lock(&self) -> std::sync::TryLockResult<VerboseGuard<'_, T>> {
        println!("acquiring {:?}", std::thread::current().id());
        let guard = self.inner.try_lock();
        if let Ok(guard) = guard {
            assert!(self.current_owner.try_lock().unwrap().is_none());
            println!("acquired {:?}", std::thread::current().id());
            *self.current_owner.try_lock().unwrap() = Some(std::thread::current().id());
            *self.last_owner.try_lock().unwrap() = Some(std::thread::current().id());
            Ok(VerboseGuard(&self, guard))
        }
        else {
            panic!("ERROR: Could not lock from {:?}; current owner is {:?}, last owner is {:?}, creator is {:?}", std::thread::current().id(), self.current_owner.try_lock().unwrap(), self.last_owner.try_lock().unwrap(), self.creator);
        }
    }
}

struct VerboseGuard<'a, T: 'a>(&'a VerboseMutex<T>, std::sync::MutexGuard<'a, T>);

impl<'a, T: 'a> VerboseGuard<'a, T> {
}

impl<T> std::ops::Deref for VerboseGuard<'_, T> {
    type Target = T;

    fn deref(&self) -> &T {
        &self.1
    }
}

impl<T> std::ops::DerefMut for VerboseGuard<'_, T> {
    fn deref_mut(&mut self) -> &mut T {
        &mut self.1
    }
}

impl<T> Drop for VerboseGuard<'_, T> {
    #[inline]
    fn drop(&mut self) {
        *self.0.current_owner.try_lock().unwrap() = None;
        println!("releasing {:?}", std::thread::current().id());
    }
}

pub fn main() {






    let size_factor = 1;  // Increase this to 10 (or more) on larger machines or the bug won't be triggered
    let batch_size = 10240 * size_factor;
    let buffer_size = 1_000_000 * size_factor;
    let num_nodes = 6_866_014 * size_factor;

    let buffers: thread_local::ThreadLocal<VerboseMutex<Vec<(usize, usize, ())>>> =
        thread_local::ThreadLocal::new();

    (0usize..=((num_nodes - 1) / batch_size))
        .into_par_iter()
        .for_each(
            |batch_id| {
                let buffer_mutex = buffers.get_or(|| {
                    println!("Allocating buffer for thread {:?} ({:?} / {})",
                        std::thread::current().id(),
                        rayon::current_thread_index(),
                        rayon::current_num_threads());

                    VerboseMutex::new(Vec::with_capacity(batch_size + 2))
                });

                println!("getting buffer {:?}", std::thread::current().id());
                let mut buffer = buffer_mutex.try_lock().unwrap_or_else(
                    |err| {
                        println!("failed to get buffer {:?}", std::thread::current().id());
                        match err {
                            std::sync::TryLockError::Poisoned(e) => panic!("Poisoned mutex: {:?}", e),
                            std::sync::TryLockError::WouldBlock => {

                                println!("ERROR: The impossible happened: thread {:?} ({:?} / {}) is trying to get its own buffer but another thread currently owns it. Waiting...", 
                                std::thread::current().id(),
                                    rayon::current_thread_index(),
                                    rayon::current_num_threads());
                                let buffer = buffer_mutex.lock().unwrap();
                                println!("ERROR: Thread {:?} ({:?} / {}) finally got its own buffer back",  
                                    std::thread::current().id(),
                                    rayon::current_thread_index(),
                                    rayon::current_num_threads());
                                buffer
                            }
                        }
                    });

                let start = batch_id * batch_size;
                let end = (batch_id + 1) * batch_size;
                (start..end).for_each(|s| {
                    for d in (s+1)..(s+10*size_factor) {
                        if d < num_nodes {
                            buffer.push((s, d, ()));
                        }
                    }
                });


                if buffer.len() > buffer_size {
                    let slice = &mut (*buffer)[..];
                    println!("sorting {:?}", std::thread::current().id());
                    buffer.par_sort_unstable_by_key(|(src, dst, _)| (*src, *dst));
                    println!("sorted {:?}", std::thread::current().id());
                } else {
                    println!("dropping (not flushed) {:?}", std::thread::current().id());
                }
            },
        );

    println!("Done.");
}
```

(you can replace `VerboseMutex` with `Mutex` in the `main` function and still get the issue, though without the logs highlighting the unexpected recursion.)

eventually, it will crash with an error like this:

```
thread '<unnamed>' panicked at 'ERROR: Could not lock from ThreadId(7); current owner is Some(ThreadId(7)), last owner is Some(ThreadId(7)), creator is ThreadId(7)', rust/src/bin/mutex_issues.rs:42:13
```

If it does not, try increasing the `size_factor` to 10 (it will consume more memory and take longer to run, though) or try a machine with fewer cores.

Here is what I get when filtering lines with `ThreadId(7)` in the output:

```
getting buffer ThreadId(7)
acquiring ThreadId(7)
acquired ThreadId(7)
sorting ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
thread '<unnamed>' panicked at 'ERROR: Could not lock from ThreadId(7); current owner is Some(ThreadId(7)), last owner is Some(ThreadId(7)), creator is ThreadId(7)', rust/src/bin/mutex_issues.rs:42:13
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
getting buffer ThreadId(7)
acquiring ThreadId(7)
sorted ThreadId(7)
```

you can see `sorting ThreadId(7)` (ie. the beginning of the par_sort_unstable_by_key call), followed by a bunch of operations in the same thread, then `sorted ThreadId(7)` (ie. end of the par_sort_unstable_by_key) call. Here is the stack trace of the panic:

```
thread '<unnamed>' panicked at 'ERROR: Could not lock from ThreadId(7); current owner is Some(ThreadId(7)), last owner is Some(ThreadId(7)), creator is ThreadId(7)', rust/src/bin/mutex_issues.rs:42:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: mutex_issues::VerboseMutex<T>::try_lock
             at ./rust/src/bin/mutex_issues.rs:42:13
   3: mutex_issues::main::{{closure}}
             at ./rust/src/bin/mutex_issues.rs:103:34
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:272:13
   5: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:853:29
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2481:21
   7: core::iter::traits::iterator::Iterator::for_each
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:856:9
   8: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/for_each.rs:55:9
   9: rayon::iter::plumbing::Producer::fold_with
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  11: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
  12: rayon_core::join::join_context::call_a::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:124:17
  13: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9
  14: std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
  15: __rust_try
  16: std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  17: std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  18: rayon_core::unwind::halt_unwinding
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  19: rayon_core::join::join_context::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:142:24
  20: rayon_core::registry::in_worker
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:984:13
  21: rayon_core::join::join_context
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:132:5
  22: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  23: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
  24: rayon_core::join::join_context::call_a::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:124:17
  25: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9
  26: std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
  27: __rust_try
  28: std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  29: std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  30: rayon_core::unwind::halt_unwinding
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  31: rayon_core::join::join_context::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:142:24
  32: rayon_core::registry::in_worker
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:984:13
  33: rayon_core::join::join_context
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:132:5
  34: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  35: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
  36: rayon_core::join::join_context::call_a::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:124:17
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9
  38: std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
  39: __rust_try
  40: std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  41: std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  42: rayon_core::unwind::halt_unwinding
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  43: rayon_core::join::join_context::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:142:24
  44: rayon_core::registry::in_worker
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:984:13
  45: rayon_core::join::join_context
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:132:5
  46: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  47: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:427:21
  48: rayon_core::join::join_context::call_b::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:129:25
  49: rayon_core::job::JobResult<T>::call::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:218:41
  50: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9
  51: std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
  52: __rust_try
  53: std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  54: std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  55: rayon_core::unwind::halt_unwinding
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  56: rayon_core::job::JobResult<T>::call
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:218:15
  57: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:120:32
  58: rayon_core::job::JobRef::execute
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:64:9
  59: rayon_core::registry::WorkerThread::execute
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:874:9
  60: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:820:17
  61: rayon_core::registry::WorkerThread::wait_until
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:803:13
  62: rayon_core::join::join_context::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:167:17
  63: rayon_core::registry::in_worker
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:984:13
  64: rayon_core::join::join_context
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:132:5
  65: rayon_core::join::join
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:105:5
  66: rayon::slice::quicksort::recurse
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/slice/quicksort.rs:830:13
  67: rayon::slice::quicksort::par_quicksort
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/slice/quicksort.rs:855:5
  68: rayon::slice::ParallelSliceMut::par_sort_unstable_by_key
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/slice/mod.rs:660:9
  69: mutex_issues::main::{{closure}}
             at ./rust/src/bin/mutex_issues.rs:138:21
  70: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:272:13
  71: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:853:29
  72: core::iter::traits::iterator::Iterator::fold
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2481:21
  73: core::iter::traits::iterator::Iterator::for_each
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:856:9
  74: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/for_each.rs:55:9
  75: rayon::iter::plumbing::Producer::fold_with
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
  76: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  77: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
  78: rayon_core::join::join_context::call_a::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:124:17
  79: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9
  80: std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
  81: __rust_try
  82: std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  83: std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  84: rayon_core::unwind::halt_unwinding
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  85: rayon_core::join::join_context::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:142:24
  86: rayon_core::registry::in_worker
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:984:13
  87: rayon_core::join::join_context
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:132:5
  88: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  89: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:427:21
  90: rayon_core::join::join_context::call_b::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:129:25
  91: rayon_core::job::JobResult<T>::call::{{closure}}
             at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:218:41
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

You can see the par_sort_unstable_by_key frame:

```
  69: mutex_issues::main::{{closure}}
             at ./rust/src/bin/mutex_issues.rs:138:21
```

indirectly called the closure again:

```
   3: mutex_issues::main::{{closure}}
             at ./rust/src/bin/mutex_issues.rs:103:34
```

Rust version: both 1.71.0 and nightly
Rayon: 1.7.0

Reproduced on both a i7-8700 (12 core) and Xeon Gold 6342 (96 core); with `size_factor = 10` on the latter.

cc @zommiommy

**Comment by Alphare** [comment]
Reproduced on an AMD Ryzen 9 7950X, since @progval was worried about their CPU being bugged. ;)

Add this to the top of the file for use with `cargo play`:
```
//# stderrlog = '*'
//# thread_local = '*'
//# rayon = '*'
```

**Comment by cuviper** [comment]
This is an instance of #592 -- the call to `par_sort` may lead to work-stealing while it waits for sub-tasks to finish, and that may steal another piece of your task that wants to use that mutex, making you re-entrant.

As a workaround, maybe your TLS can have an `Option<Vec<T>>` for the buffer that you `take` out while you're working with it, rather than holding the `Mutex` locked? Then store it back as `Some` when you're done. When re-entrancy finds it `None`, you can allocate a new one instead. Maybe you can even keep `Vec<Vec<T>>` to save multiple allocations just in case, with `pop` to use and then `push` it back (or `push` the new one).

(I'm assuming the buffer is to save allocation time, not needing re-used data between instances.)

**Comment by progval** [comment]
I removed inner parallelism instead, it had a lower impact on performance.

Thanks again for your help
