### ISSUE TITLE
execute_strings_split and clone_str tests failure

### ISSUE THREAD

**Issue by pheki** [rayon-rs/rayon#504]
When executing `cargo +nightly test` it **sometimes** will fail with panic in iter::test::execute_strings_split (it looks like the byte index is always the same). I experienced it once with clone_str too but never both on the same test.

I'm using the nightly-x86_64-unknown-linux-gnu toolchain in an up to date arch linux.

```
failures:

---- iter::test::execute_strings_split stdout ----
	thread 'iter::test::execute_strings_split' panicked at 'byte index 6289 is not a char boundary; it is inside '\u{0}' (bytes 6288..6289) of `assertion failed: a.is_some()assertion failed: counter.load(Ordering::SeqCst) < 2048assertion failed: b.iter().all(|&x| x == a.len() - 1)assertion failed: a.iter().all(|&x| x == a.len() - 1)assertion failed: resul`[...]', /checkout/src/libcore/str/mod.rs:2234:5

failures:

---- clone_str stdout ----
	thread 'clone_str' panicked at 'byte index 2849 is not a char boundary; it is inside 'C' (bytes 2848..2849) of `clone_binary_heapclone_btree_mapclone_btree_setclone_hash_mapclone_hash_setclone_linked_listclone_vec_dequeclone_optionclone_resultclone_rangeclone_strclone_vecclone_adaptorsclone_emptyclone_onceclone_repeatclone_splitter`[...]', /checkout/src/libcore/str/mod.rs:2234:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by cuviper** [comment]
Strange, it's claiming the indexes are in the middle of single-byte characters?

**Comment by Bilkow** [comment]
Yes, I also couldn't figure it out.

The backtrace indicates the bug happens inside this `for`:

```
for &(string, _) in &tests {
    let serial: Vec<_> = string.lines().collect();
    let parallel: Vec<_> = string.par_lines().collect();
    assert_eq!(serial, parallel);
}
```

backtrace:
```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::str::slice_error_fail
             at /checkout/src/libcore/str/mod.rs:0
  10: <str as core::fmt::Debug>::fmt
             at /checkout/src/libcore/str/mod.rs:1892
             at /checkout/src/libcore/option.rs:376
             at /checkout/src/libcore/str/mod.rs:1892
             at /checkout/src/libcore/str/mod.rs:1666
             at /checkout/src/libcore/fmt/mod.rs:1607
  11: <&'a T as core::fmt::Debug>::fmt
             at /checkout/src/libcore/fmt/mod.rs:1558
  12: <&'a T as core::fmt::Debug>::fmt
             at /checkout/src/libcore/fmt/mod.rs:1558
  13: core::fmt::builders::DebugInner::entry
             at /checkout/src/libcore/fmt/builders.rs:0
  14: core::fmt::builders::DebugList::entry
             at /checkout/src/libcore/fmt/builders.rs:415
  15: core::fmt::builders::DebugList::entries
             at /checkout/src/libcore/fmt/builders.rs:426
  16: <[T] as core::fmt::Debug>::fmt
             at /checkout/src/libcore/fmt/mod.rs:1742
  17: <alloc::vec::Vec<T> as core::fmt::Debug>::fmt
             at /checkout/src/liballoc/vec.rs:2144
  18: <&'a T as core::fmt::Debug>::fmt
             at /checkout/src/libcore/fmt/mod.rs:1558
  19: core::fmt::write
             at /checkout/src/libcore/fmt/mod.rs:1076
             at /checkout/src/libcore/fmt/mod.rs:1023
  20: core::fmt::Write::write_fmt
             at /checkout/src/libcore/fmt/mod.rs:223
  21: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
  22: rayon::iter::test::execute_strings_split
             at src/iter/test.rs:115
  23: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libtest/lib.rs:1442
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:817
  24: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
```

**Comment by cuviper** [comment]
I'm going to assume this was an old compiler bug, but feel free to reopen or file anew if it comes up again.
